### ISSUE TITLE
Villager trades editor issue

### ISSUE THREAD

**Issue by rusnuker** [Ruukas97/Infinity-Item-Editor#20]
Trades editor has a little problem: it's impossible to set MaxUses for a trade. I need to edit raw NBT data to customize it.

IIE 1.12.2

**Comment by ThiemeH** [comment]
Added in [e46ccc6](https://github.com/Ruukas97/Infinity-Item-Editor/commit/e46ccc679083e330d2eb623a182cdd29365148ff)
