### ISSUE TITLE
How do I remove items from The Realm?

### ISSUE THREAD

**Issue by rusnuker** [Ruukas97/Infinity-Item-Editor#21]
I tried to use NBT Explorer, but that's just slow.

**Comment by Ruukas97** [comment]
You can press G on an item, whole hovering it in the creative tab.
You should join the discord server, if you have more questions :)

**Comment by rusnuker** [comment]
It is not working! realm.nbt is not updating, after Minecraft restart every removed item is back!

**Comment by Ruukas97** [comment]
I'm not sure. It should work.
Make sure you don't have the file open in NBTExplorer at the same time, and I guess it also matters if you close Minecraft properly, rather than just closing the window

**Comment by rusnuker** [comment]
Not working. NBTExplorer is closed, the world saved, game closed with Quit Game button.

**Comment by Ruukas97** [comment]
Hmm, I wonder what the issue could be... There might be an item causing issues, or if the file becomes too large.
Otherwise, I'm not sure what could be wrong. The saving works almost the same as vanilla hotbar saving.
