### ISSUE TITLE
Color formatting issue

### ISSUE THREAD

**Issue by rusnuker** [Ruukas97/Infinity-Item-Editor#22]
The "§" cymbol gets ignored when pasted in with a bunch of NBT data.

Before: 
![image](https://user-images.githubusercontent.com/49472785/158209326-2ec1eab7-33fe-42e7-8a55-bfc6cb34e25e.png)

After:
![image](https://user-images.githubusercontent.com/49472785/158209421-67d5d1f5-623e-4468-bd96-3cf5490b9897.png)

**Comment by ThiemeH** [comment]
Could you please post the NBT and the exact steps you did to make the problem occur? I can't seem to reproduce.

**Comment by rusnuker** [comment]
1. Copy an NBT data of the item with colored name/lore
![image](https://user-images.githubusercontent.com/49472785/159107562-bb2b1676-ecdc-4166-b426-7202d286fee3.png)
2. Paste it
![image](https://user-images.githubusercontent.com/49472785/159107567-55f3c67c-2e3e-4980-8426-78947d8623eb.png)
