### ISSUE TITLE
FEATURE ADD : duplicate enchantment on item.

### ISSUE THREAD

**Issue by xAstroBoy** [Ruukas97/Infinity-Item-Editor#3]
Since a Youtuber recently discovered one thing, you are able to add the same enchantment multiple times!

I tested , and is confirmed!

Ex: trying this command, i added sharpness multiple times

/give marcocorriero minecraft:diamond_sword 1 0 {ench:[{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767},{id:16,lvl:32767}],Unbreakable:1}

**Comment by Zerotiger** [comment]
Thank you for suggesting, but I try to avoid redundant nbt data

**Comment by marcocorriero** [comment]
> Thank you for suggesting, but I try to avoid redundant nbt data

Add a option if you could stack it over and over.

**Comment by xriqn** [comment]
> > Thank you for suggesting, but I try to avoid redundant nbt data
> 
> Add a option if you could stack it over and over.

That's easily fixed with some kind of string reader tbh, if I had git on my PC I'd be trying to fix it myself to lighten the load on Ruukas.
~Telephone from TF (Roger on the discord)

**Comment by Ruukas97** [comment]
The rewrite that is being work on will support this.
