### ISSUE TITLE
[Bug] Copying /give command doesn't work

### ISSUE THREAD

**Issue by Someone671** [Ruukas97/Infinity-Item-Editor#4]
I'm now on 1.12.2 testing with IIE and I found out that copying the /give command (if you hold down shift and clicked the "Drop" button), the /give command would look something like this:
`/give @p minecraft:grass 1 0 1xtile.grass@0`
I thought this was some new additions to commands in IIE, but when i executed it, it errors out.

I did this to see how to /give items with a colored name, but now I just have to wait...

**Comment by Ruukas97** [comment]
Sorry I did not get back to you before now. I added a feature that lets you get the command of an item in your inventory by pressing Ctrl + C while hovering that item. This command should work correctly.
I will fix the other command to work as well.
Thank you for reporting.
