### ISSUE TITLE
Void sometimes causes player kick on BungeeCord servers

### ISSUE THREAD

**Issue by LDS-XiaoYe** [Ruukas97/Infinity-Item-Editor#5]
The lateset version.
When you use BungeeCord or other branches,player was kicked wihen they jump to another server.

reason:
![image](https://user-images.githubusercontent.com/53298022/73146541-3b545c80-40ee-11ea-9fb6-423eec0fbf46.png)

i used to change bungeecord core, but it is unuseful. 

bungeecord console say:
 ServerConnector [server] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
0d02

And my mc version is 1.12.2

**Comment by Ruukas97** [comment]
Thank you for reporting. Can I have the full crash report and maybe server up?

**Comment by LDS-XiaoYe** [comment]
> Thank you for reporting. Can I have the full crash report and maybe server ip?

no crash. the server core is CatServer-Async .
my server is in China and need special minecraft client.

**Comment by Ruukas97** [comment]
Okay. I will try to reproduce.
It only happens when Infinity Item Editor is installed?

**Comment by LDS-XiaoYe** [comment]
- 

> Okay. I will try to reproduce.
> It only happens when Infinity Item Editor is installed?

No. there are other mods.
But when i install Infinty Item Editor,the problem produced.

**Comment by Ruukas97** [comment]
I haven't set up a bungeecord server before. So, I am not sure how to do it. I downloaded https://github.com/Luohuayu/CatServer/releases , but it's all in Chinese.

**Comment by Ruukas97** [comment]
If you can send me steps to reproduce, I will try my best.

**Comment by LDS-XiaoYe** [comment]
you can set a lobby server and main server in bungeecord.
if you want to jump to other servers, you can use chestcommands or bungeecord commands "/server".
then use forge client which install Infinty Item Editor join and jump to catserver-async.

**Comment by LDS-XiaoYe** [comment]
if u can not understand chinese, you can use Google translate or ask me

**Comment by Ruukas97** [comment]
I found the issue. It is related to "void" which can be disabled in config. I am working on a fix now.

**Comment by LDS-XiaoYe** [comment]
thank you ,i will wait.

**Comment by Ruukas97** [comment]
New release will be up on CurseForge within a few hours (could be less than 1 hour).

**Comment by Ruukas97** [comment]
It's available now

**Comment by LDS-XiaoYe** [comment]
i updated ,but the problem reproduced.
bungeecord report:
encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
0d00

**Comment by Ruukas97** [comment]
I apologize. I will try to reproduce again.

**Comment by Ruukas97** [comment]
I can't reproduce it anymore.

**Comment by LDS-XiaoYe** [comment]
i also,thank u.
