### ISSUE TITLE
Crash while rendering screen 

### ISSUE THREAD

**Issue by mikucat0309** [Ruukas97/Infinity-Item-Editor#7]
Minecraft Version: 1.11.2
Forge Version: 13.20.1.2588
Mod Version: Infinity-0.13.2-MC1.11.2
[Crash report](https://gist.github.com/mikucat0309/0e48d2bd1f1ea7985e3a9a16fa944d4a)

I'm playing a spigot server.
When I press "U" in creative mode, it suddenly crash.
Trying a few times, it crash every time, even in survival mode.

**Comment by Ruukas97** [comment]
I can't really provide support for the 1.11.2 backport. I recommend using the 1.12.2 version.
I would need the crash report to identify what went wrong.

**Comment by mikucat0309** [comment]
I see. Thanks for response👍
crash-report is here: https://gist.github.com/mikucat0309/0e48d2bd1f1ea7985e3a9a16fa944d4a

**Comment by xriqn** [comment]
> I can't really provide support for the 1.11.2 backport. I recommend using the 1.12.2 version.
> I would need the crash report to identify what went wrong.

It appears to be some kind of unterminated array, unfortunately I can't find the code path specified in the error in the code. If you want to talk more about this, come to the support channel on the discord and speak to me (Roger), Ruukas or Thieme.

**Comment by Ruukas97** [comment]
I'm pretty sure it has to do with the nbt preview

**Comment by Ruukas97** [comment]
As it stands now, I can't provide support for the 1.11.2 version. Maybe I will do another backport in the future, in which it should be fixed.
