### ISSUE TITLE
[Suggestion] Allow Item Editor in Survival

### ISSUE THREAD

**Issue by Xarmat-GitHub** [Ruukas97/Infinity-Item-Editor#8]
### Allow Item Editor in Survival - via Config

I am using this tool to balance weapons and armors in my pack.
But switching every time to creative mode change a small value and change back to survival is a long way to go.
Allowing to use this mod in survival would be great and can be turned off in the config as soon the modpack get realest.

Thanks for the nice tool and keep up the nice work. 👍 

___
**Solution:**
- Skip game mode check

**Comment by cybertelx** [comment]
This would only work on singleplayer, as multiplayer servers don't accept packets to change the NBT of any item from a user in survival mode. Otherwise, hackers and griefers would wreak havoc with unlimited TNT and 32k weapons.

**Comment by Xarmat-GitHub** [comment]
Ok, didn't know about the server restriction.
But having this feature in local single player would be great for Modpack Makers.
So it could be be worth. Would love to see this (less game switching while testing and changing gear for test fights etc.)

**Comment by return-true-if-false** [comment]
> Ok, didn't know about the server restriction. But having this feature in local single player would be great for Modpack Makers. So it could be be worth. Would love to see this (less game switching while testing and changing gear for test fights etc.)

I don't know if you even need this anymore (you have had a long time to just switch game modes) but this pull request should implement what you want.

**Comment by ThiemeH** [comment]
As of now there's no plan to make it work in survival. The mod is considered a tool rather than a 'cheat'. And like [cybertelx](https://github.com/cybertelx) said, it wouldn't work on servers even if we added it. Closing this issue (months later)
